options(BioC_mirror="https://mirrors.westlake.edu.cn/bioconductor")
options("repos" = c(CRAN="https://mirrors.ustc.edu.cn/CRAN/"))
if(!require(installr))install.packages('installr')
if(!require(devtools))install.packages('devtools')
if(!require(stringr))install.packages('stringr')
if(!require(BiocManager))install.packages('BiocManager')
if(!require("qs"))BiocManager::install("qs")
if(!require(limma))BiocManager::install('limma')
if(!require(future))BiocManager::install('future')
if(!require(Seurat))BiocManager::install('Seurat')
if(!require(DoubletFinder))devtools::install_github('chris-mcginnis-ucsf/DoubletFinder')
if(!require(SoupX))install.packages("SoupX")
if(!require(dplyr))BiocManager::install('dplyr')
if(!require(magrittr))BiocManager::install('magrittr')
if(!require(ggplot2))BiocManager::install('ggplot2')
if(!require(findPC))devtools::install_github("haotian-zhuang/findPC")
#scatter用conda install  bioconductor-scater 
if(!require(scater))devtools::install_github("davismcc/scater", build_vignettes = TRUE, keep_install_file=TRUE)
if(!require(scater))BiocManager::install("scater")
if(!require(harmony))install.packages('harmony')
if(!require(celldex))BiocManager::install('celldex')
if(!require(scRNAseq))BiocManager::install('scRNAseq')
if(!require(SingleR))BiocManager::install('SingleR')
if(!require(BiocParallel))BiocManager::install('BiocParallel')
if(!require(ComplexHeatmap))BiocManager::install('ComplexHeatmap')
if(!require(CellChat))devtools::install_github("sqjin/CellChat")
if(!require(cellcall))devtools::install_github("ShellyCoder/cellcall")
if(!require(monocle3))devtools::install_github('cole-trapnell-lab/monocle3')
if(!require(SeuratWrappers))remotes::install_github('satijalab/seurat-wrappers')
if(!require(tidyverse))install.packages("tidyverse")
if(!require(velocyto.R))devtools::install_github("velocyto-team/velocyto.R")
#windows用手动加载boost环境方法安装，看noenote
#-----------------------------测试多核运算--------------------------------------
library("parallel")
makecore <- function(workcore,memory){
  if(!require(Seurat))install.packages('Seurat')
  if(!require(future))install.packages('future')
  plan("multisession", workers = workcore)
  options(future.globals.maxSize= memory*1024*1024**2)
}
cl <- detectCores()
makecore(cl, 256)
cl <- makeCluster(cl)
#insert your functions
plan("sequential")
stopCluster(cl)
rm(cl)
